language: node_js
node_js:
    - "15"
services:
  - mysql
# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=test
# 在 install 前執行的指令
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS life_guard default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize sequelize-cli mysql2 -g
  - sequelize db:migrate
script:
  - echo "skipping tests"
# 在執行測試之前的指令
# before_script:
  
deploy:
  provider: heroku
  api_key:
    secure: 294de0a4-0ad5-4a77-88e0-20aae9559363
  app: lifeguard2020
  on:
    repo: ZenYu-Tech/lifeguard-backend